[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "seshotake", email = "seshotake@gmail.com"},
]
dependencies = [
    "tk>=0.1.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
